### ISSUE TITLE
report: 일부 table의 enum 타입 field가 varchar 타입으로 생성됨

### ISSUE THREAD

**Issue by zzo3ozz** [gusto-umc/Gusto-Server#14]
### 🐛 Bug 개요
- #5 에서 작성된 entity의 enum 타입 필드들이 db 내에서 varchar 타입으로 생성되고 있음

### 📷 Screenshots
  ![image](https://github.com/gusto-umc/Gusto-Server/assets/90233522/0a410095-4417-4926-9b78-54bf5eb3497a)

### ✏️ Description
  ![image](https://github.com/gusto-umc/Gusto-Server/assets/90233522/c8da2ad7-3534-48cd-a7ba-81e1aeb23466)
Enumerated 어노테이션보다 columnDefinition이 우선 적용되는 것으로 추정됨

**Comment by zzo3ozz** [comment]
![image](https://github.com/gusto-umc/Gusto-Server/assets/90233522/4af823f2-dce0-4fe9-a2ec-9225acc8f7da)
다음과 같이 refactor 하여 수정

**Comment by kchaeeun** [comment]
아고 제가 놓쳤던 부분인데 감사합니다!
